### ISSUE TITLE
Search index crawl delay on full index rebuild

### ISSUE THREAD

**Issue by bobharing** [Kentico/xperience-by-kentico-azure-ai-search#31]
**Is your feature request related to a problem? Please describe.**
When rebuilding the index from the admin the index builds without seemingly any delay between indexed items. When having thousands of pages this basically means when we crawl the pages by doing http request we would be making a lot of requests to the site increasing the performance requirements. 

**Describe the solution you'd like**
A setting to set the index delay item per index item when doing a rebuild of the full index. For example in the appsettings having
```
{
...
     "IndexItemDelay": 2000
...
}
```
 will have the indexing a page every 2 seconds.

**Describe alternatives you've considered**
Another approach is to have this index respect the Crawl-delay value in the robots.txt. We can set the useragent of the crawler it would make sense to have it read the robots.txt and delay the crawling accordingly.
```
User-agent: SearchCrawler
Crawl-delay: 10
```

**Additional context**

**Comment by seangwright** [comment]
@bobharing do you have any thoughts about this being a global application setting managed in code (`appsettings.json`) vs per-index configuration managed in the administration UI?

**Comment by bobharing** [comment]
@seangwright Well that depends on what the vision would be.

Having it as part of the index setup in the admin will mean that we want to have this control per index. I can imagine some use cases have large indexes and others smaller (and less resource intensive depending on the pages it crawls). So you might want to be more granular on the delay per index. Plus you get the advantage of being able to modify this delay without having to do a redeployment (or modifying the appsettings.json directly which is not possible on SaaS environments)

If we want to apply just a singular blanket rule, then I would prefer to have it applied in appsettings.json instead of course.

**Comment by bkapustik** [comment]
Hello, optional `IndexItemDelay` has been added to address this request in the release [v4.1.1](https://github.com/Kentico/xperience-by-kentico-azure-ai-search/releases/tag/v4.1.1)
